version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      - echo build for release
      - npm install gitbook-cli -g
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - gitbook install
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - gitbook build
  post_build:
    commands:
      - aws s3 sync _book/ s3://aws-quickstart/website/ --region cn-northwest-1
      - echo Build completed on `date`
      - aws cloudfront create-invalidation --distribution-id EULXNHQDDXCOU --paths "/*"
artifacts:
  files:
    - _book/**/*
  discard-paths: yes
