apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-server
  namespace: kube-jenkins
spec:
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: jenkins-server
      containers:
      - name: jenkin-server
        image: 182335798701.dkr.ecr.cn-northwest-1.amazonaws.com.cn/jenkins-update-repo:v1
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
         - echo starting;
           /sbin/tini -- /usr/local/bin/jenkins.sh;
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 50000
          name: agent
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        volumeMounts:
        - name: jenkinshome
          mountPath: /var/jenkins_home
      nodeSelector:
          failure-domain.beta.kubernetes.io/zone: cn-northwest-1a
      securityContext:
        fsGroup: 1000
      volumes:
      - name: jenkinshome
        persistentVolumeClaim:
          claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
  namespace: kube-jenkins
  labels:
    app: jenkins-server
spec:
  selector:
    app: jenkins-server
  type: LoadBalancer
  ports:
  - name: web
    port: 8080
    targetPort: web
  - name: agent
    port: 50000
    targetPort: agent
